services:
  backend:
    build:
      context: ./mern-demo
      dockerfile: server/Dockerfile
    ports:
      - "5000:5000"
    environment:
      MONGODB_URI: ${MONGODB_URI}
    env_file:
      - ./mern-demo/.env
    networks:
      - mern-network

  frontend:
    build:
      context: ./mern-demo/client
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    depends_on:
      - backend
    networks:
      - mern-network

networks:
  mern-network:
    driver: bridge
